import { pg as p } from "../page.js";

const C = "/images/cover-golden-auto.png";
const A = "/images/panel-chotu-1.png";
const B = "/images/panel-chotu-2.png";
const D = "/images/panel-chotu-3.png";
const E = "/images/panel-chotu-4.png";

export const goldenAuto = {
  id: "golden-auto",
  title: "The Golden Auto",
  issue: "Book 03",
  genre: "Action comedy",
  place: "Old Delhi",
  minutes: 13,
  accent: "#d97706",
  mood: "kite",
  pdf: "/pdfs/The-Golden-Auto.pdf",
  cover: C,
  hero: "Chotu Malik & Sonu the Auto",
  logline:
    "A talking auto-rickshaw and a boy with goggles become Delhi’s unofficial rescue service for lost treasures, stubborn grandmothers, and homework that tries to escape.",
  pages: [
    p(C, "Chandni Chowk at the hour of kites. Gravity is a suggestion.", "Sonu", "Meter’s off. Adventure’s on. Hold the handle.", "VROOM",
      "The lane is a debate between spice, horns, and wedding bands practising in different keys. Above it, a golden auto-rickshaw treats altitude as a civic right."),
    p(A, "Chotu found Sonu sleeping under a tarp, humming an old filmi horn.", "Chotu", "Autos don’t talk. Also they don’t fly. We are already two impossibilities late.", "HONK",
      "Sonu’s headlights make expressions. This is illegal in several ways, none of which are listed in the transport code because the code lacks imagination."),
    p(B, "Dadi’s wedding necklace is missing, and with it a whole family’s ability to breathe normally.", "Dadi", "If it is gone, the wedding photos will start lying.", "GASP",
      "Chotu loves his grandmother the way Delhi loves chaat: messily, daily, without a backup plan. He promises the necklace before he has a method."),
    p(D, "A smuggler van thinks spice lanes are a racetrack.", "Sonu", "They have a van. We have personality. And altitude.", "SKRRR",
      "Sacks of chilli burst like red weather. Chotu learns that hanging off a flying auto is excellent for courage and terrible for homework corners."),
    p(D, "The van driver is not a mastermind. He is a man who said yes to a bad uncle.", "Chotu", "Pull over or I will tell your mother you steal from dadi-types.", "YELL",
      "This is more effective than karate. The driver weeps, which is inconvenient at sixty kilometres an hour even when sixty is partly vertical."),
    p(B, "The necklace returns. Dadi inspects it like a jeweller who has survived empires.", "Dadi", "Keep the goggles, beta. The city needs witnesses.", "JINGLE",
      "She feeds Sonu a marigold. Sonu blushes in chrome. Chotu realises they have accidentally started a business with no GST category."),
    p(A, "Word travels faster than meters.", "Neighbour", "My spectacles went to the mosque roof. Also my dignity.", "SHOUT",
      "Tuesday: spectacles. Wednesday: a cricket bat that believed it was a bird. Thursday: a politician’s toupee, which they return anonymously for everyone’s safety."),
    p(E, "Diwali night writes gold over the old city.", "Chotu", "Tonight we deliver lost things. Tomorrow, maybe fractions.", "BOOM",
      "Fireworks argue with stars. Sonu threads alleys that do not exist on maps because maps are cowards. A boy waves from a rooftop as if hailing a perfectly normal miracle."),
    p(B, "A lost wedding card leads them to a bride who has locked herself in with doubt.", "Bride", "If I go out, I have to mean it.", "KNOCK",
      "Chotu is twelve and therefore an expert in meaning it. He does not give a speech. He gives her the card and a samosa still warm, which is the correct theology."),
    p(D, "A rival appears: a black SUV with tinted spirituality and a fake GPS voice.", "SUV", "This city belongs to people who pay for air.", "GRR",
      "Sonu’s reply cannot be printed in full. The chase uses laundry lines as hurdles and a startled cow as a roundabout."),
    p(A, "They lose the SUV in a lane so narrow it requires an apology.", "Sonu", "I was assembled by a mechanic who believed in folklore. That is my papers.", "CLANK",
      "Chotu checks Sonu for dents. There are dents. They are shaped like stories."),
    p(E, "A teacher flags them down with a missing attendance register.", "Teacher", "If this is gone, several children will become officially imaginary.", "PAPER",
      "They find it in a tree, being read by pigeons with strong opinions about tardiness. The teacher offers full marks in moral science and a warning about seatbelts that do not exist."),
    p(B, "Rain. Even flying autos must consider puddles as a lifestyle.", "Chotu", "If we crash, I am telling Amma it was educational.", "SPLASH",
      "Sonu lands, poorly, beside a chaat stall. The stall owner charges them for three plates because miracles make people hungry."),
    p(D, "The bad uncle returns with paperwork claiming Sonu is stolen municipal property.", "Uncle", "Golden? That’s a paint job and a hallucination.", "STAMP",
      "Chotu’s Dadi arrives with a wooden rolling pin and a marriage certificate older than the uncle’s confidence. The paperwork develops second thoughts."),
    p(C, "A hand-painted board appears: LOST? FLAG THE GOLDEN AUTO.", "Narrator", "Delhi has a million vehicles. Only one keeps secrets and altitude.", "HONK HONK",
      "Tourists photograph it. Locals pretend not to. The board is already peeling, which means it belongs."),
    p(A, "Chotu tries to keep a timetable. The city refuses.", "Chotu", "We can do lost keys before school if the keys agree.", "BELL",
      "He is late anyway. His teacher looks at the goggles, at the marigold pollen, and writes PRESENT IN SPIRIT, which is not a real category and therefore accurate."),
    p(B, "Night courier work: a violin to a sad man in Daryaganj.", "Sad man", "I sold it. Then I heard the street without it.", "NOTE",
      "They do not ask how a sold violin got lost. Lost is a country with its own customs. The man plays one scale and the lane becomes briefly polite."),
    p(E, "Sonu wants a holiday. Chotu suggests the Yamuna, which is a complicated holiday.", "Sonu", "I will fly over it and think clean thoughts.", "WHOOSH",
      "The river is tired and holy and full of the city’s unfinished homework. They drop a garland and do not pretend that is enough. Then they return a lost cricket ball to a boy who had started inventing despair."),
    p(D, "Exam season. Even smugglers take a break. Lost geometry boxes do not.", "Chotu", "Compass, protractor, and one very emotional eraser.", "SCRIBBLE",
      "They complete the set two minutes before the bell. Chotu sits the exam with chilli still in his hair. He names an angle after Sonu and still gets it right."),
    p(B, "Dadi packs tiffin for two: one human, one vehicle.", "Dadi", "Chrome also needs protein. Do not argue with science.", "TIN",
      "Sonu eats oil and affection. Chotu eats paratha. The lane smells like a victory that will have to be repeated tomorrow."),
    p(A, "A small girl flags them with a missing dog that is actually under her own charpai.", "Chotu", "Sometimes lost means hiding on purpose.", "WOOF",
      "They still take a victory lap so the dog can enjoy being found. This is good policy."),
    p(C, "Evening settles like a honk that became a lullaby.", "Narrator", "Keep the goggles on. The city misplaces itself daily.", "FADE HORN",
      "Somewhere a necklace stays found. Somewhere a register stays official. And a golden auto, illegal in all the ways that matter, waits under a tarp, humming, ready to be late for the right reasons."),
  ],
};
