import { pg as p } from "../page.js";

const C = "/images/cover-monsoon-meera.png";
const A = "/images/panel-meera-1.png";
const B = "/images/panel-meera-2.png";
const D = "/images/panel-meera-3.png";
const E = "/images/panel-meera-4.png";

export const monsoonMeera = {
  id: "monsoon-meera",
  title: "Monsoon Meera",
  issue: "Book 01",
  genre: "Folk fantasy",
  place: "Kerala backwaters",
  minutes: 14,
  accent: "#0e7c7b",
  mood: "rain",
  pdf: "/pdfs/Monsoon-Meera.pdf",
  cover: C,
  hero: "Meera Rainbinder",
  logline:
    "When the village well cracks dry, a girl who can hear clouds must walk the old rain-road, bargain with a sulking monsoon, and teach a whole generation the song they forgot.",
  pages: [
    p(C, "Alappuzha. Forty-one days without a honest drop.", "Narrator", "The well sang once. Now it only coughs dust.", "DRY WIND",
      "Paddy fields lie like cracked pottery. Coconut palms rattle with a thirst that has begun to sound like argument. In the lane, water is counted in steel tumblers and sideways looks."),
    p(E, "Amma rations tea as if it were medicine, because it nearly is.", "Amma", "If you climb that roof again, the sky will think we are beggars.", "CLINK",
      "Meera’s mother has survived worse summers, but never one that made the temple pond look ashamed. She hides worry in extra pickle and in telling her daughter to stay practical."),
    p(A, "Meera climbs anyway. Roofs, in her family, have always been a kind of pulpit.", "Meera", "I can hear you sulking. Come down and argue properly.", "DRIP",
      "Dawn makes the tiles look like wet coins even when they are dry. Meera cups her ear toward a bruise-coloured cloud that has been circling the backwaters like a thought nobody wants to finish."),
    p(D, "The monsoon answers with elephant patience and a child’s temper.", "Monsoon", "They forgot the old songs. Why should I remember their fields?", "RUMBLE",
      "It is not a god exactly, and not a weather report. It is weather with a memory. It remembers processions, it remembers roofs painted with rice-flour, it remembers being thanked."),
    p(E, "Amma finds her on the steps with salt on her eyelashes that is not from the sea.", "Amma", "Talking to clouds will not fill a pot.", "HUSH",
      "Meera tells her the truth in the smallest possible sentences. Amma does not laugh. In this village, strange things are only strange the first time they save a crop."),
    p(A, "The bargain begins the way all Kerala bargains begin: with insult, then tea, then terms.", "Meera", "If they forget, I will remind them. If you forget, I will shout until the sky gets embarrassed.", "CRACK",
      "The monsoon wants a chorus. Not a museum song, not a school-function song. The one grandmothers used when the first rain smelled like hot earth and crushed pepper."),
    p(D, "Meera walks the rain-road: jetty, shrine, the house of the woman who still keeps a rain-drum.", "Meera", "Loan me the drum. I will return it louder.", "TAP TAP",
      "Old Leelamma’s wrists remember rhythms her tongue claims to have lost. She teaches Meera three beats and a pause that means please without kneeling."),
    p(B, "Children are terrible at reverence and excellent at repetition.", "Child", "Again! The part where the cloud gets scolded!", "SPLASH",
      "In the temple courtyard Meera drills a choir of cousins, ferry-boys, and one extremely serious goat. The song returns like a relative who swore they would never visit and then brought sweets."),
    p(D, "A contractor arrives with bottled water and a smile that invoices the future.", "Contractor", "Forget folklore. Sign here. I will pipe you civilisation.", "STAMP",
      "He wants the dry well as proof that the village must sell its bank to a private tank. Meera’s monsoon bristles. Weather hates being used as a sales chart."),
    p(A, "Meera refuses the pen. The cloud refuses the man’s umbrella.", "Meera", "Civilisation here still knows how to share a tumbler.", "NO",
      "The contractor’s papers wilt without rain, which is a petty miracle and therefore the best kind. He leaves promising lawyers. The goat remains unimpressed."),
    p(E, "Night. Amma sets out a fourth cup, empty, for a guest who is not a person.", "Amma", "If it comes in, wipe its feet. I just swept.", "STEAM",
      "Hospitality is the village’s oldest technology. Meera understands, suddenly, that the song was never magic. It was a way of making room."),
    p(D, "The monsoon tests them with a wind that knocks the drum into the canal.", "Monsoon", "Retrieve it without complaining, and I will consider being weather again.", "WHOOSH",
      "Meera dives. Canal water in a drought is a muddy argument. She comes up with the drum and a leech on her ankle, which she names temporarily after the contractor."),
    p(B, "The first true rain arrives like a rumour that turns out to be a wedding.", "Narrator", "Dust learns, in one afternoon, how to be mud with opinions.", "DOWNPOUR",
      "People shout. People laugh. Someone starts the song wrong and is lovingly bullied into the right key. The well does not overflow yet; it only remembers how."),
    p(B, "Banana leaves become drums. The goat finally keeps time.", "Amma", "That girl talks to weather like it owes her rent.", "THUNDER",
      "Meera does not dance at first. She watches the cloud’s face for cheating. Finding none, she lets herself be sixteen and soaked and loudly incorrect about the lyrics."),
    p(A, "At the height of the storm the monsoon asks for one more term.", "Monsoon", "Keep a listener in every generation. I will not audition twice.", "BOOM",
      "Meera looks at the children, at Amma, at the drum. She nods the way you nod when you accept a job that will never pay in rupees and will always pay in mango season."),
    p(E, "Morning after. The world smells like iron, earth, and fried shallots.", "Amma", "Eat. Saving a village is not an excuse to skip breakfast.", "SIZZLE",
      "They eat in wet clothes because dry clothes are a tomorrow problem. Outside, frogs hold a meeting more organised than the panchayat."),
    p(D, "The contractor’s boat returns, sees the full well, and develops a sudden interest in other districts.", "Meera", "Tell your lawyers the sky already signed.", "HONK",
      "It is not a legal argument. It is better. The village copies the rain-song into school copybooks beside multiplication tables."),
    p(B, "On the forty-second dusk, the well overflows and nobody pretends to be dignified.", "Child", "Meera akka, teach the part that makes lightning clap.", "LAUGH",
      "Meera teaches them the pause instead, the please. Lightning, she says, is just the sky showing off, and showing off should never be the chorus."),
    p(A, "The monsoon leaves a raindrop on Meera’s earring that refuses to evaporate.", "Monsoon", "Call me when they forget. I like being argued with.", "SOFT RAIN",
      "It hangs there like a second ear. On dry days it ticks, faintly, to remind her that weather is a relationship, not a season."),
    p(E, "Weeks later, a girl from the next jetty arrives with a cracked pot and a rumour.", "Visitor", "They say you can scold clouds. Ours has been rude for a month.", "KNOCK",
      "Amma looks at Meera. Meera looks at the drum. The goat looks like it is updating its calendar."),
    p(D, "Meera packs pickle, the rain-drum, and a voice already hoarse from practice.", "Meera", "I am not a goddess. I am a reminder with good lungs.", "FOOTSTEPS",
      "The backwaters stitch villages together more honestly than roads. She takes the ferry knowing the job is larger than one well, and lighter than despair."),
    p(C, "Somewhere over the palms, a cloud keeps pace, pretending not to follow.", "Narrator", "Thus begins the quiet career of Monsoon Meera, listener-for-hire.", "DISTANT THUNDER",
      "The fields drink. The well sings under its breath. And a girl in a yellow raincoat walks the rain-road with an argument already prepared, just in case the sky gets proud again."),
  ],
};
