import { pg as p } from "../page.js";

const C = "/images/cover-night-mail.png";
const A = "/images/panel-tara-1.png";
const B = "/images/panel-tara-2.png";
const D = "/images/panel-tara-3.png";
const E = "/images/panel-tara-4.png";

export const nightMail = {
  id: "night-mail",
  title: "Night Mail of Howrah",
  issue: "Book 02",
  genre: "Noir mystery",
  place: "Howrah Junction",
  minutes: 14,
  accent: "#3d4a8a",
  mood: "noir",
  pdf: "/pdfs/Night-Mail-of-Howrah.pdf",
  cover: C,
  hero: "Inspector Tara Sen",
  logline:
    "Letters vanish from the night mail. Inspector Tara boards a train that should have stopped in 1947 and learns that some addresses take seventy years to finish walking.",
  pages: [
    p(C, "Platform 9 after midnight smells of wet iron and unfinished goodbyes.", "Narrator", "Living trains keep timetables. The other one keeps promises.", "WHISTLE",
      "Howrah Junction never truly sleeps; it only lowers its voice. Porters dream standing up. Tea boils like a rumour. In the booking office, three sacks of mail have gone light as if the paper learned to fly."),
    p(A, "The stationmaster wants a thief. Tara wants a pattern.", "Tara", "Thieves take wallets. This took handwriting.", "STAMP",
      "She copies dispatch numbers into a notebook that already knows too many names. The missing envelopes are not random. They are all last letters: apologies, land details, a child’s drawing of a river."),
    p(A, "A tea-seller named Bhola swears he saw a blue engine nobody scheduled.", "Bhola", "It did not stop, madam. It remembered.", "CLINK",
      "Bhola’s family has sold tea here since before the bridge learned its own name. He is not poetic except when steam is involved. Tara believes him because his hands shake in a professional way."),
    p(D, "Fog thickens until the rails look like a sentence with the verb removed.", "Tara", "If you are a train, you will have to argue with a lantern.", "FOGHORN",
      "She walks past the last official lamp. Her brass lantern — grandfather’s, partition-era, never polished enough — throws a coin of gold that the fog tries to swallow and fails."),
    p(D, "Letters burst from a carriage window like white birds that finally remember the way.", "Tara", "Those are not stolen. They are overdue.", "WHOOSH",
      "She does not run like a film hero. She runs like someone who has missed too many living people to miss the dead as well. Envelopes slap her coat, addressed in inks that went out of fashion with certain countries."),
    p(B, "Inside: passengers of pale light, each holding a letter they died still carrying.", "Ghost clerk", "Partition scrambled the addresses. We have been sorting ever since.", "HUSH",
      "The carriage is a travelling post office. Rubber stamps click without hands. A boy in a school cap holds a letter to a sister whose city changed its name twice while he was busy being history."),
    p(B, "Tara sits because standing feels like disrespect.", "Tara", "I close cases. You seem to keep them warm.", "SIT",
      "The clerk’s face is kind in the way of people who have had enough time to stop being cruel. He shows her bags labelled with stations that exist, stations that don’t, and one labelled simply HOME."),
    p(E, "She reads names that still have grandsons in Shyambazar and granddaughters in Dhaka.", "Tara", "Give me the last living addresses. I will walk them in daylight.", "PAPER",
      "Some recipients have died. Some have become buildings. A surprising number are still arguing with pigeons on rooftops. Tara writes until her pencil is a stub and her lantern is a friend."),
    p(A, "A living inspector boards at the next halt, flashlight first.", "Living inspector", "Sen? You are on an unauthorised… what is this fog?", "CLICK",
      "He cannot see the ghosts. He sees Tara talking to empty seats, which is a career problem. She asks him to hold her notebook and please not arrest the upholstery."),
    p(B, "The ghost train passes through his chest like a moral.", "Ghost clerk", "The living are always so sure emptiness is empty.", "WHOOM",
      "He sits down hard. Tara does not enjoy being right this way. She tells him to drink Bhola’s tea and consider a transfer to lost property, which is at least honest."),
    p(D, "A letter refuses to leave the rack: addressed to a house that became a flyover.", "Tara", "Then we deliver it to the ground. Roads still remember plots.", "SCREECH",
      "The train slows over a place that used to be a courtyard. Tara drops the envelope through a gap in the world. Somewhere below, a night-watchman dreams of his grandmother’s handwriting and weeps without knowing why."),
    p(B, "The boy in the school cap wants to know if his sister kept the drawing.", "Boy", "I put a river on it. She liked rivers more than borders.", "SNIFF",
      "Tara cannot lie to the dead. She says she will find out. Finding out, in her profession, is a synonym for not sleeping."),
    p(E, "Dawn. A rooftop in north Kolkata. An old man waters plants in leftover tins.", "Old man", "My sister drew like that. She went across and then the letters stopped.", "BIRDSONG",
      "Tara places the drawing in his hands. He does not ask for credentials. Grief recognises official stamps even when the government that issued them no longer agrees with itself."),
    p(E, "He asks if the boy is all right.", "Tara", "He is on time, finally.", "SOFT",
      "Which is not the same as alive, and both of them know it. The old man puts the drawing under a brick so the wind cannot practise partition again."),
    p(A, "Bhola listens to her report as if it were cricket scores from a better universe.", "Bhola", "More tea. Ghosts are thirsty work.", "POUR",
      "Tara’s superiors want a form. She writes: MAIL DELIVERED BY UNUSUAL MEANS. Nobody files it correctly. The file grows a quiet reputation."),
    p(B, "Night after night the engine returns, lighter.", "Ghost clerk", "We are down to the stubborn ones. The letters that wanted to be poems.", "CHUG",
      "Tara boards when she can. She learns the names of stations the way other people learn prayers. She starts keeping extra envelopes for the living who still do not know how to say sorry."),
    p(D, "A new theft: not letters this time, but the lanterns of porters.", "Tara", "Someone is trying to make the dead miss their stop.", "SNATCH",
      "A scrap dealer has been paid to steal old light. Tara finds him, not with violence, but with a bill of sale that includes his own unanswered letter to a father in 1982. He returns the lanterns and also, accidentally, his courage."),
    p(C, "The ghost engine bows once in ordinary fog.", "Narrator", "Some detectives close cases. Tara delivers them.", "BELL",
      "Commuters complain about delays. They always do. None of them know their delays are sometimes a kind of mercy."),
    p(B, "The clerk offers her a stamp of her own.", "Ghost clerk", "For the letters you will owe the world later.", "THUNK",
      "She almost refuses. Then she thinks of every unsent message in her own drawer. She pockets the stamp. It is cold and slightly kind."),
    p(E, "On her day off she writes to a cousin she has not called in nine years.", "Tara", "If a ghost train can sort 1947, I can sort a phone number.", "RING",
      "The cousin cries, then insults her cooking, then invites her for fish. This, too, is investigation."),
    p(A, "Howrah exhales. The night mail of the living leaves on time, almost embarrassed.", "Bhola", "Madam, if my letters ever get lost—", "WHISTLE",
      "Tara taps the lantern. Bhola laughs, then does not, then packs extra ginger in her tea as insurance."),
    p(C, "Platform 9 keeps a spare timetable in a language nobody teaches.", "Narrator", "Inspector Tara Sen, specialist in overdue love.", "FADE",
      "Fog will come again. Letters will try to remain brave. And a woman with a brass lantern will walk past the last official lamp because some evidence only shows up in old light."),
  ],
};
