import { pg as p } from "../page.js";

const C = "/images/cover-solar-goat.png";
const A = "/images/panel-tashi-1.png";
const B = "/images/panel-tashi-2.png";
const D = "/images/panel-tashi-3.png";

export const solarGoat = {
  id: "solar-goat",
  title: "Goat of the Solar Wind",
  issue: "Book 08",
  genre: "Mountain adventure",
  place: "Nubra Valley",
  minutes: 13,
  accent: "#3d4a8a",
  mood: "dust",
  pdf: "/pdfs/Goat-of-the-Solar-Wind.pdf",
  cover: C,
  hero: "Tashi Dolma",
  logline:
    "A Ladakhi tinkerer and a goat with a solar saddle race a sandstorm to bring light back to a school that winter is trying to erase.",
  pages: [
    p(C, "Sunrise in Nubra looks like a match struck against the Himalaya.", "Narrator", "Wind here is a teacher. It does not care if you took notes.", "WHOOSH",
      "Tashi Dolma is seventeen, repairs things other people call dead, and has a goat named Kalsang who believes in voltage the way monks believe in patience."),
    p(A, "The saddle is her invention: light panels, old batteries, prayer-flag wiring that is only slightly theological.", "Tashi", "If it works, it is science. If it is pretty, that is a side effect.", "SPARK",
      "Village aunties trust her because she fixed the butter-churn motor and did not lecture them about progress. Kalsang chews a wire, is scolded, chews a biscuit instead."),
    p(D, "The school’s batteries fail in a week of cloud that feels personal.", "Headteacher", "Children can learn in the dark. They should not have to.", "CLICK",
      "Tashi inventories every working cell in three hamlets. The map of power looks like a thin necklace. She decides to walk the necklace with a goat."),
    p(B, "A sandstorm stands up on the dunes like a brown god with poor boundaries.", "Tashi", "Kalsang, if we die, I am blaming your snack schedule.", "ROAR",
      "They run anyway. Running toward weather is a family habit. Her grandmother crossed worse for a library book, a story Tashi uses as fuel."),
    p(A, "Mid-storm, a panel cracks. Tashi tapes it with cloth meant for a winter sleeve.", "Tashi", "Sorry, jacket. The school is colder than a shoulder.", "RIP",
      "Kalsang plants his feet in the way of goats who have read the land longer than engineers. They angle the remaining panel like a sail toward a rumour of sun."),
    p(D, "A truck is stuck, tourists arguing with GPS, GPS arguing with God.", "Tourist", "Is there a charger in this century?", "BEEP",
      "Tashi does not take their power bank. She takes their extra water and leaves them a cairn pointing to the road they actually wanted. Kalsang refuses a selfie, which improves the century."),
    p(B, "The storm thins. The school is a dark tooth on the valley.", "Headteacher", "You look like a proverb with dust in its teeth.", "GASP",
      "They plug the saddle into the tired battery bank. Light returns like a shy guest, then like a festival. Children cheer in two languages and one wordless yell."),
    p(C, "Night class happens: fractions, a song, a debate about whether goats can be engineers.", "Child", "Kalsang sir should get a stamp.", "LAUGH",
      "Tashi draws a circuit on the blackboard. The chalk squeaks. Someone falls asleep and is allowed to, because darkness had been stealing sleep all week."),
    p(A, "Morning. A monk offers butter tea and a warning about pride.", "Monk", "Fixing light is good. Becoming the only light is a trap.", "SIP",
      "Tashi starts a notebook titled OTHER HANDS. She will teach two younger kids the solder, even if they burn a hole in a sock. Socks are replaceable. Knowledge of sockets is not."),
    p(B, "A company wants to brand the goat.", "Executive", "Imagine the campaign. Authentic. Elevating. Limited-edition trekking merch.", "PING",
      "Tashi says Kalsang is not a campaign. The executive writes DISRUPTIVE LOCAL PARTNER and flies away. The valley, unbothered, continues to be high."),
    p(D, "Winter closes one road. The other road becomes a rumour.", "Tashi", "Then we store summer in boxes, like pickle.", "WIND",
      "They build a small library of charged batteries labelled with jokes. When a joke is bad, the battery still works, which is a useful lesson about standards."),
    p(A, "Kalsang falls sick. Tashi forgets every circuit.", "Tashi", "Eat. If you die I will have to talk to people more.", "BLEAT",
      "The vet is a day away. The aunties arrive with herbs and insulting nicknames that have healed worse. Kalsang lives, vindicated, and steals a glove as tax."),
    p(B, "A second storm, smaller, as if copying homework.", "Narrator", "Copying is how weather and students both improve.", "GUST",
      "The two apprentices take the saddle this time. Tashi watches from the school steps with her heart in her throat and her hands in her pockets on purpose."),
    p(D, "They succeed badly — light flickers, then holds.", "Apprentice", "We taped it with a song. Is that allowed?", "HUM",
      "Tashi says if it holds, it is allowed. She writes the song in the notebook under OTHER HANDS, because methods should be honest about their ingredients."),
    p(C, "Stars over Nubra are so sharp they look like they could cut wire.", "Tashi", "Good. We might need them as spare sun.", "STILL",
      "She lies on her back beside a goat who smells of dust and victory. The school hums. Humming is a kind of prayer that does not require anyone to be impressive."),
    p(A, "Her father, a driver, comes home and checks the panels like a man checking a child’s forehead.", "Father", "Do not become so useful they forget you are young.", "PAT",
      "Tashi promises nothing of the sort and then sleeps twelve hours, which is a kind of promise."),
    p(B, "In Leh, a workshop invites her to speak. She brings Kalsang, who eats a name-tag.", "Tashi", "The goat is the co-author. Cite him or the circuit fails.", "MURMUR",
      "Someone from a ministry takes notes. Someone from a village takes her number. She prefers the second number."),
    p(D, "Back home, the children draw Kalsang with rays like a small sun that chews.", "Child", "When I grow up I will fix wind.", "COLOUR",
      "Tashi does not say wind cannot be fixed, only met. She says start with a torch. Starting small is how mountains are crossed."),
    p(A, "She oils the saddle, patches the cracked panel properly, returns the winter sleeve cloth as a patch of honour on the jacket.", "Tashi", "See? The school gave you a medal.", "STITCH",
      "The jacket looks ridiculous and beloved. Perfect."),
    p(C, "Wind again, teacher again, no exam, only weather.", "Narrator", "Tashi Dolma, mechanic of leftover sun.", "WHOOSH",
      "The valley does not get easier. It gets shared. And a girl and a goat with a solar saddle keep a school from becoming a rumour, which is one of the better uses of light."),
    p(D, "Last bell of the term rings on stolen sunshine.", "Headteacher", "Homework: thank the goat and the girl, not in that order if you are afraid of horns.", "BELL",
      "Laughter. Batteries full. Snow on the high edges like a white comment in the margin of the world."),
    p(B, "They walk home slower than the storm required, because slow is a kind of wealth.", "Tashi", "Kalsang, if you chew the wiring I will make you a hat.", "BLEAT",
      "He chews the hat-threat thoughtfully. The sun, professional as ever, keeps hitting the panels as if it had been in on the plan from the first match-strike morning."),
  ],
};
