import { pg as p } from "../page.js";

const C = "/images/cover-stepwell-clock.png";
const A = "/images/panel-vikram-1.png";
const B = "/images/panel-vikram-2.png";
const D = "/images/panel-vikram-3.png";

export const stepwellClock = {
  id: "stepwell-clock",
  title: "The Stepwell Clock",
  issue: "Book 06",
  genre: "Time fantasy",
  place: "Adalaj, Gujarat",
  minutes: 14,
  accent: "#b45309",
  mood: "stone",
  pdf: "/pdfs/The-Stepwell-Clock.pdf",
  cover: C,
  hero: "Vikram Adalaj",
  logline:
    "A boy with a brass clock that ticks backwards must descend a stepwell where festivals of five centuries are late for each other — and put time back where the stairs can bear it.",
  pages: [
    p(C, "The stepwell is a throat the earth uses to drink sky.", "Narrator", "Tourists see geometry. Vikram hears appointments.", "ECHO",
      "He is fourteen and unofficially the well’s intern. His mother sells tickets. His job, unspoken, is to notice when the water reflects the wrong century’s jewellery."),
    p(A, "The brass clock was in a niche behind a carved elephant smaller than a thumb.", "Vikram", "You were not on the inventory list. Typical.", "TICK",
      "It ticks backwards only when someone above is in a hurry for the wrong reasons. Today it ticks like a scold. A developer wants a glass elevator in the well ‘for accessibility and Instagram’."),
    p(B, "Water becomes a clock-face. A time-keeper spirit sits in the centre, unimpressed.", "Time-keeper", "Your century is noisy. It keeps borrowing minutes it will not return.", "GONG",
      "The spirit wears white and gold and an expression of a clerk at closing time. Vikram, who has been late to maths, recognises the look immediately."),
    p(A, "On the stairs, a wedding from 1582 collides with a school trip from Tuesday.", "Bride of 1582", "Is that a glowing brick in his hand? Rude.", "GASPS",
      "Children photograph a marriage that is trying to finish its varmala. The well groans. Stone does not like being a waiting room."),
    p(B, "The developer arrives with drones, which the well interprets as large insects with no manners.", "Developer", "History should be comfortable or it should move.", "BUZZ",
      "Vikram’s mother argues in Gujarati that comfort is a bench in the shade, not an elevator through a sacred throat. The drones dip toward the water and forget which way is up."),
    p(A, "Vikram descends. Each landing is a year that refuses to queue.", "Vikram", "Excuse me. Festival of lights, please wait behind the monsoon of 1983.", "STEP STEP",
      "He is not brave so much as busy. Busy is how fourteen survives impossible errands. The clock grows warm against his chest like a second heart with opinions."),
    p(D, "A drowned watchman from a drought year wants to know if the rains came back.", "Watchman", "I fell counting empty pots.", "DRIP",
      "Vikram cannot change that death. He can tell the truth: the rains came, went, came again, and people still argue about who owns clouds. The watchman looks oddly comforted by the arguing."),
    p(B, "The time-keeper offers a deal: reset the well, but Vikram will miss three days of his own life.", "Time-keeper", "Payment is always personal. Clocks are snobs that way.", "TOCK",
      "Three days. He will miss a cricket match and a cousin’s birthday and, possibly, a maths test. He almost smiles, then feels guilty, then agrees because the well is larger than his calendar."),
    p(A, "Resetting looks like ushering. He points. He bows. He scolds a Mughal courier for running on the wet step.", "Vikram", "No running. The stone remembers slips.", "SHH",
      "The courier is indignant, then ashamed, then helpful. Together they unwind a knot of processions until the stairs can see their own feet."),
    p(D, "Above, the elevator pitch continues, now with a minister.", "Minister", "Think of tourism revenue as a kind of prayer.", "MURMUR",
      "Vikram’s mother does not throw anyone in, which should be noted as heroism. She throws facts instead: water table, carvings, the word irreversible."),
    p(B, "The spirit shows Vikram a future where the well is a mall with a stepwell theme.", "Vikram", "That future has no echo. I can tell.", "SILENCE",
      "Theme restaurants do not echo; they play playlists. Vikram, who has grown up inside an echo, finds this more frightening than ghosts."),
    p(A, "He places the clock against the water. Backwards ticking becomes a circle, then a still.", "Clock", "Thank you. I was getting dizzy on purpose.", "STILL",
      "Festivals return to their landings. Tuesday’s school trip becomes merely Tuesday. A teacher counts heads and does not know she almost counted a dynasty."),
    p(D, "Vikram climbs out missing three days. His cousin is older by a cake.", "Mother", "You were in the well. I told them you had fever. Fever is a kind of time.", "HUG",
      "He eats leftover birthday sweets that are slightly stale and therefore sacred. The developer’s drones are in a tree, being lectured by parakeets."),
    p(C, "The minister wants a photo with the boy who ‘saved heritage’.", "Vikram", "Please photograph the elephant smaller than a thumb. It did more.", "CLICK",
      "They photograph Vikram anyway. He makes a face that ruins two posters and improves one unofficial stall’s T-shirt, years later."),
    p(B, "The time-keeper remains, quieter, a watermark.", "Time-keeper", "When they hurry again, you will hear appointments in the plumbing.", "SOFT GONG",
      "Vikram nods. He does his missed maths. He gets a surprising number of answers right, as if some of the centuries had been good at fractions."),
    p(A, "A girl from the school trip returns alone, having seen too much and needing a word for it.", "Girl", "Was the bride real?", "WHISPER",
      "Vikram says real is a crowded word. He says the bride was busy. He gives her a ticket stub and a rule: do not run on the stairs, not because of guards, because of respect."),
    p(D, "Night. Lanterns — the legal kind — line the steps for a conservation walk.", "Mother", "No elevators. People can walk if the story is worth the knees.", "LANTERN",
      "Elderly visitors sit often. Sitting is also looking. Vikram carries water. The well approves of water that is shared, not piped as spectacle."),
    p(B, "The brass clock now ticks forward, ordinary, almost boring.", "Vikram", "Boring is a luxury the stairs earned.", "TICK",
      "He keeps it anyway. Ordinary time is a gift you only notice after you have ushed five centuries into a queue."),
    p(A, "A small wrong reflection returns on a festival night: one dancer from the wrong decade.", "Vikram", "You missed your landing. Come. The drum is still going.", "DRUM",
      "He walks her down, not as a hero, as a volunteer usher in a temple of gravity. She smiles with a mouth from another makeup style and vanishes mid-step, on time."),
    p(D, "The developer opens a cafe across the road instead, called STEP INN.", "Developer", "I can take a hint if it costs less than stone.", "CUP",
      "The chai is fine. The well does not mind competition that stays on the other side of the ticket counter."),
    p(C, "Moon in the circle of water, round as a clock that has decided to behave.", "Narrator", "Vikram Adalaj, intern of impossible appointments.", "NIGHT BIRD",
      "Buses leave. Stone cools. And a boy who spent three days he will never get back sleeps without nightmares, because the stairs, at last, are only stairs — until they aren’t, and he will be there with a clock and a scold."),
    p(A, "In the morning he sells tickets and tells no one the price of a minute.", "Vikram", "Keep your phone in your pocket on the last flight of stairs.", "STAMP",
      "Some visitors obey. The well, which has learned to like this century a millimetre more, ticks along with the ordinary brass, and that is as close as time comes to saying thank you."),
  ],
};
