import { pg as p } from "../page.js";

const C = "/images/cover-ten-shadows.png";
const A = "/images/panel-priya-1.png";
const B = "/images/panel-priya-2.png";
const D = "/images/panel-priya-3.png";
const E = "/images/panel-priya-4.png";

export const tenShadows = {
  id: "ten-shadows",
  title: "Temple of Ten Shadows",
  issue: "Book 04",
  genre: "Adventure",
  place: "Hampi",
  minutes: 14,
  accent: "#b45309",
  mood: "stone",
  pdf: "/pdfs/Temple-of-Ten-Shadows.pdf",
  cover: C,
  hero: "Priya Rao",
  logline:
    "An archaeologist finds a relic that wakes Hampi’s stone dancers — and a smuggling chain that wants history silent, portable, and priced.",
  pages: [
    p(C, "Moon through a broken vimana. The pillars have been waiting for a listener.", "Narrator", "Hampi does not ruin. It rehearses.", "ECHO",
      "Boulders look like a conversation the earth started and never finished. Priya’s camp is a stove, a permit, and a stubbornness her professors called unprofessional and her bones call correct."),
    p(E, "By lantern she copies a frieze the way other people copy phone numbers.", "Priya", "If I miss a wrist-angle, I miss a century’s joke.", "SCRATCH",
      "A small shadow sits beside the notebook like a cat made of dusk. It does not take the pencil. It is, for now, polite."),
    p(A, "The gold box is not hidden so much as postponed.", "Priya", "Easy. I am not here to steal the sentence. I am here to finish reading it.", "SHHNK",
      "Ten carved dancers peel off stone like wet ink. Their ankles remember drums. Their faces remember audiences who brought oranges and arguments."),
    p(A, "They do not attack. They audit.", "Shadow dancer", "Keeper or taker? We have a test. It involves feet.", "HUM",
      "Priya’s boots are not dance shoes. She bows anyway, badly, which the shadows find charming because honesty photographs well in moonlight."),
    p(D, "A flashlight cuts the corridor — battery-powered entitlement.", "Smuggler", "Relics belong to whoever can carry them out.", "CLICK",
      "He has a buyer in a city that likes old things the way it likes quiet servants. He has a gun he does not know how to make historically accurate."),
    p(D, "Priya fights with provenance, which is slower than a bullet and harder to dodge.", "Priya", "Carry it out and the shadows follow you home. Ask me how I know.", "GRIND",
      "She does not, in fact, want him to ask. She has seen a collector’s apartment where the curtains danced without wind until the man learned to return a bronze lamp."),
    p(E, "The shadows freeze mid-reach, insulted by the beam.", "Priya", "Light is not the enemy. Greed is just badly aimed light.", "FLICKER",
      "She lowers her torch to the floor. The smuggler’s flashlight looks suddenly lonely. In the half-dark, the dancers look like law."),
    p(B, "He grabs the box. His shadow lengthens in a way shadows should not.", "Smuggler", "It is light. Why is it heavy in my sleep already?", "CLACK",
      "The box contains a contract: whoever owns it hosts the rehearsal. Ten performances a night. No intermission. No applause that is not earned."),
    p(D, "Priya offers a trade: the box stays, his name leaves the site report’s criminal appendix if he walks.", "Priya", "I prefer my villains tired, not legendary.", "STEP",
      "Pride almost ruins him. Then one dancer copies his walk so accurately he sees himself as a thief and is embarrassed in a way no court can schedule."),
    p(B, "The box returns to its niche. Ten shadows bow and become carving.", "Shadow dancer", "Keepers may look. Takers must dance until their feet remember stone.", "HUM",
      "Priya’s permit, in this moment, feels like a love letter the ASI did not mean to write. She photographs the niche, not the gold. Gold photographs like a lie."),
    p(E, "Sunrise. She writes a report the museum will only half believe.", "Priya", "Good. Belief is optional. Respect is not.", "BIRDSONG",
      "She includes measurements, maps, and one sentence in a footnote: THE SITE IS OCCUPIED. Her editor will try to delete it. The sentence will crawl back."),
    p(A, "A week later, tourists come with the kind of quiet that is actually phones on silent.", "Guide", "Do not touch the pillars. They have opinions.", "SHUTTER",
      "Priya watches a child bow to a dancer by accident, tripping. The stone seems pleased. She does not put this in the brochure. Brochures are cowards too."),
    p(D, "The smuggler’s buyer arrives in linen, smiling like a brochure.", "Buyer", "Name a number. History is a market.", "CHIME",
      "Priya names a number: zero, plus the cost of his flight home, plus a lecture she will not let him skip. He calls her emotional. The shadows call him off-key."),
    p(B, "Night two of the test he did not know he signed.", "Buyer", "Make them stop dancing in the minibar.", "THUD",
      "He returns, sweating linen, and funds a conservation fence instead. Priya accepts the fence and not the apology, which is still in first draft."),
    p(E, "She teaches a field school how to look without taking.", "Priya", "Your pencil is a guest. Your ego is luggage. Leave the luggage on the bus.", "SCRATCH",
      "Students complain, then produce the best drawings of their lives. One of them will become a problem in twenty years. Priya writes his name down anyway, hoping to be wrong."),
    p(A, "A storm. Lightning makes the temple look briefly brand new.", "Narrator", "Stone likes to remember its opening night.", "CRACK",
      "Priya sits in the mandapa and lets rain argue with dust. The small dusk-cat shadow returns and sits on her permit, which is the highest blessing available."),
    p(C, "She dreams of ten dancers rehearsing a harvest that no longer uses those exact grains.", "Dancer", "Keep the steps even if the crop changed.", "SOFT DRUM",
      "Waking, she adds a chapter to her notes titled CONTINUITY. It will annoy people who like history in glass."),
    p(D, "Police want a simpler story: heroine, villain, box.", "Officer", "Just tell us if it is treasure.", "RADIO",
      "Priya says it is a responsibility with gold around it. They write TREASURE anyway. She initials the form like someone signing a truce with language."),
    p(B, "On leaving day the niche looks ordinary, which is how the best secrets dress.", "Priya", "I will come back when the moon is rude again.", "PACK",
      "The boulders do not wave. Waving is for people. Still, a hawk turns once over the vimana in a way that feels like correspondence."),
    p(E, "In Bengaluru a committee asks why her photos contain extra darkness.", "Chair", "We can crop the shadows.", "PROJECTOR",
      "Priya smiles the smile of someone who has met worse committees than this, including one made of stone. She says cropping is how empires begin."),
    p(A, "She keeps a torch battery labelled HAMPI, as if light had a hometown.", "Priya", "If I forget my manners, drain yourself.", "CLICK",
      "It is a joke and a vow. Archaeologists collect both."),
    p(C, "Moonrise again, somewhere, on stone that is practising being eternal.", "Narrator", "Priya Rao, reader of unfinished sentences.", "OWL",
      "The ten shadows sleep in their carving. The box stays unpriced. And a woman on a night bus south of the boulders sleeps with dust still in her hair, which is how you can tell the work was real."),
  ],
};
