import { pg as p } from "../page.js";

const C = "/images/cover-tiffin-map.png";
const A = "/images/panel-leela-1.png";
const B = "/images/panel-leela-2.png";
const D = "/images/char-leela.png";

export const tiffinMap = {
  id: "tiffin-map",
  title: "The Tiffin Map of Pune",
  issue: "Book 09",
  genre: "City fable",
  place: "Pune",
  minutes: 13,
  accent: "#d97706",
  mood: "kite",
  pdf: "/pdfs/The-Tiffin-Map-of-Pune.pdf",
  cover: C,
  hero: "Leela Kulkarni",
  logline:
    "A cycle courier finds a tiffin that projects the city’s secret kindnesses — and a logistics company trying to flatten every lane into a paid straight line.",
  pages: [
    p(C, "Pune rain makes bicycles philosophical and commuters late.", "Narrator", "Leela rides as if the city were a conversation she could still win.", "RING RING",
      "Twenty-two, yellow jersey, calves like argument. She delivers idlis, legal notices, and once a kitten, which was not on the app and therefore the best job."),
    p(A, "The tiffin on her rack is not her order. It hums. It throws a map of alleys onto wet tar.", "Leela", "If you are GPS, you are the first one I like.", "HUM",
      "The map shows not shortcuts for speed but shortcuts for care: a bench where an old man shares shade, a stall that gives extra for fever, a lane that avoids a dog who is afraid of bells."),
    p(B, "First delivery the tiffin insists on: a verandah she would have skipped as inefficient.", "Aaji", "We stopped ordering. We thought the city had become only apps.", "KNOCK",
      "Leela hands over dal-rice still warm. The couple eat like people who had been practising being forgotten. She stays for tea because the map, glowing, draws a circle labelled SIT."),
    p(D, "Her dispatcher wants numbers, not sitting.", "Dispatcher", "Time is money, Leela. Money is also money.", "BEEP",
      "She says sitting is infrastructure. He does not have a KPI for that. The app flags her. She flags the app in her mind as a troll under a bridge."),
    p(A, "A logistics firm, FASTRA, paints new arrows on old lanes, erasing the kind ones.", "FASTRA", "Straight lines. No stories. Stories crash the algorithm.", "PAINT",
      "The tiffin map flickers where the arrows go. Leela understands: they are not painting roads, they are painting over memory."),
    p(B, "She starts a counter-route called the Slow List, written on brown paper at the idli stall.", "Stall uncle", "I will pin it next to the extra-chilli. People already look there for truth.", "PIN",
      "Couriers gather, suspicious, then hungry, then converted. A boy on a scooter adds a clinic that opens the back door for night-shift bruises."),
    p(A, "FASTRA offers her a job in a helmet that looks like a threat.", "Manager", "Join us. We will let you keep the yellow as nostalgia.", "SMILE",
      "Leela keeps the yellow as present tense. She leaves the meeting via a lane the tiffin draws in the carpet, which is impossible and therefore accurate."),
    p(C, "Monsoon thickens. The map shows a flooded underpass and a grandmother who does not know.", "Leela", "Reroute, aaji. The water is doing performance art.", "SPLASH",
      "She carries the grandmother’s bags up a longer hill. The tiffin glows like a proud stove. Leela’s lungs write a complaint and then withdraw it."),
    p(B, "Someone steals the tiffin. Pune without it looks suddenly rectangular.", "Leela", "Give it back or I will deliver your conscience by hand.", "YELL",
      "The thief is a FASTRA intern who thought he was collecting data. The tiffin burns his fingers with a smell of methi. He returns it, crying about his KPIs, which is almost growth."),
    p(D, "Leela teaches him the Slow List. He quits, then asks if quitting counts as a delivery.", "Intern", "I can still ride. I just cannot flatten.", "SOB",
      "She puts him on the idli-stall pinboard as REFORMED, a category the city needs."),
    p(A, "Night. She cycles past FC Road, map dim, just a girl in yellow.", "Leela", "Even magic should take a weekly off.", "CRICKETS",
      "Without the glow she still remembers two kind lanes. That is the point. Tools should retire into people."),
    p(B, "A wedding order: fifty tiffins, one missing groomsman hiding from his own party.", "Groomsman", "If I go in, I have to dance. I have dignity.", "DJ",
      "Leela, who has no patience for dignity that starves a grandmother, also has patience for panic. She walks him in through a kitchen door the map labels MERCY."),
    p(C, "FASTRA’s arrows wash off in a rain that seems to have read the Slow List.", "Narrator", "Paint is temporary. Banyans are not.", "DOWNPOUR",
      "The firm sues the weather in a press release. Pune laughs, which is a civic sport."),
    p(A, "The tiffin’s map starts including Leela’s own tiredness as a red zone.", "Tiffin", "Eat. You are becoming a straight line.", "RUMBLE",
      "She eats at the verandah couple’s, who have started cooking extra on purpose. Reciprocity: the oldest app."),
    p(B, "A child asks if the bicycle is famous.", "Leela", "The lanes are famous. I am just the rumour that uses gears.", "GIGGLE",
      "She lets him ring the bell once. He rings it twelve times. The dog who fears bells is on a different street, thankfully, taking a personal day."),
    p(D, "Winter morning, breath like smoke, jersey over a sweater, still yellow enough.", "Leela", "If I get a car I will have to apologise to my calves.", "PUFF",
      "She does not get a car. She gets a second bell for the Slow List riders, a tiny parliament of rings."),
    p(A, "The tiffin, satisfied, begins to look like an ordinary dabba.", "Leela", "Stay ordinary. I have the map in my knees now.", "CLICK",
      "Ordinary is not the end of magic. It is magic that has successfully become habit."),
    p(B, "Last delivery of the book: a tiffin to her own mother, who never orders, who always waits.", "Mother", "You look like you have been talking to streets again.", "DOOR",
      "Leela says streets talk back if you ring politely. They eat. The bicycle leans on the wall like a relative."),
    p(C, "Pune at dusk, neither app nor myth, just lanes with names the GPS still mispronounces.", "Narrator", "Leela Kulkarni, courier of unprofitable care.", "RING",
      "Somewhere a verandah stays warm. Somewhere an intern learns a longer route. And a yellow bicycle writes, again, a map that cannot be flattened without losing the point of the city."),
    p(A, "On Sunday she oils the chain and does not check the app.", "Leela", "If they need me, they can use a bell. Ancient technology. Works in rain.", "DRIP",
      "The tiffin sits on the rack, quiet. A lane waits, crooked, kind, inefficient, alive."),
    p(B, "Monday. She rides. The map, now invisible, still turns her left where left means someone eats.", "Leela", "Straight lines are for exams. Cities are for detours.", "WHIRR",
      "A grandmother waves. An intern waves. A FASTRA arrow, faded, points nowhere useful. Leela rings twice: once for the delivery, once for the street."),
    p(C, "Rain again, philosophical again, on time in the only way rain is.", "Narrator", "If you are lost in Pune, look for yellow. Then look where yellow refuses to hurry.", "SOFT HORN",
      "The tiffin map of Pune is not a product. It is a practice. And a woman with gears for a heartbeat keeps practising, which is how a city stays edible."),
  ],
};
