import { pg as p } from "../page.js";

const C = "/images/cover-walking-ghazals.png";
const A = "/images/panel-sana-1.png";
const B = "/images/panel-sana-2.png";
const D = "/images/char-sana.png";

export const walkingGhazals = {
  id: "walking-ghazals",
  title: "The Ghazals That Walked",
  issue: "Book 07",
  genre: "Musical mystery",
  place: "Lucknow",
  minutes: 13,
  accent: "#0e7c7b",
  mood: "noir",
  pdf: "/pdfs/The-Ghazals-That-Walked.pdf",
  cover: C,
  hero: "Sana Qureshi",
  logline:
    "When Lucknow’s old ghazals stand up and leave their singers, Sana Qureshi follows the notes through chowks and courtyards to a silence being sold as luxury.",
  pages: [
    p(C, "The Imambara courtyard holds moonlight the way a throat holds a note.", "Narrator", "Some songs are so old they have learned to walk.", "AALAP",
      "Sana is nineteen, trains in a room with a leaking cooler, and still believes a taan can rearrange a city if you aim it kindly. Tonight the city aims back."),
    p(A, "During riyaz, a couplet leaves her mouth, becomes a gold bird, and hops out the jali.", "Sana", "Come back. We were in the middle of a promise.", "FLUTTER",
      "She chases it in embroidered teal through lanes that smell of kebabs and naphthalene. The bird is faster than dignity."),
    p(A, "Other singers report the same theft: not recordings, the living tune.", "Ustad", "My raag packed a bag. In my time, raags had loyalty.", "SIGH",
      "An ustad who taught her father sits on a charpai looking emptied, like a radio unplugged. Sana brings him tea and a notebook. He draws the bird’s flight-path from memory of the notes."),
    p(B, "The birds roost, briefly, on a billboard for a gated complex called HUSH ESTATES.", "Billboard", "Experience silence. Starting two crore.", "NEON",
      "Sana understands the crime before she can prove it. Silence, in Lucknow, was never empty; it was the pause between couplets. Someone is bottling the pause and selling it as prestige."),
    p(D, "The developer is a man who claps on the wrong beat even when there is no music.", "Developer", "Culture is a noise complaint with better lighting.", "CLAP",
      "His show-flat has soundproofing thick enough to suffocate a thumri. On the glass table, a cage of gold notes sleeps like jewellery that used to be alive."),
    p(A, "Sana cannot break in like a film thief. She books a viewing as a possible buyer’s niece.", "Sana", "My uncle loves quiet. He also loves being lied to, apparently.", "DOORBELL",
      "The salesgirl is kind and tired and recites amenities. Sana recites a couplet under her breath. The cage rattles. The salesgirl pretends not to hear, then hears, then looks afraid for her job and a little saved."),
    p(B, "At dusk Sana sings in the courtyard the way you open a window in a locked room.", "Sana", "If you remember the second line, you remember the way home.", "SUR",
      "Notes lift from the cage without keys. They are ragged, underfed. A security guard weeps without knowing the words, which is how you can tell they are the right words."),
    p(A, "The developer calls it vandalism. The chowk calls it weather.", "Crowd", "Let her finish. We have been humming with holes in us.", "MURMUR",
      "Phones come out, then go down, because some things are cheaper to keep in the throat. A child starts the second line incorrectly and is corrected by three aunties in harmony, a legal system."),
    p(D, "Sana’s mother wants her to take a bank exam.", "Mother", "Birds do not pay rent, jaan.", "PAPER",
      "Sana says neither do stolen silences, until they do, at two crore. Her mother, who once sang at weddings, looks at her hands. The argument becomes a duet, which is to say it becomes love with extra volume."),
    p(B, "They return the ghazals to singers like returning stray cats who know their own roofs.", "Ustad", "Sit. Your mouth has been doing police work.", "SIT",
      "He feeds her nihari. She sleeps on the floor and dreams of couplets standing in a queue for water, patient as Lucknow’s summers are not."),
    p(C, "HUSH ESTATES rebrands, weakly, as GARDEN HEIGHTS.", "Developer", "Fine. Keep your noise. It is bad for resale anyway.", "CRANE",
      "The soundproofing is donated to a library that actually wanted quiet for reading, which is a different, allowed silence. Sana attends the donation to make sure the walls do not eat ghazals on the side."),
    p(A, "A remaining bird refuses to go home: a song nobody claims.", "Bird", "I am from a poet who died without a disciple.", "CHIRR",
      "Sana learns it the slow way, line by line, from the bird’s impatient hops. She will not record it first. She will teach two children so it cannot be caged by being unique."),
    p(B, "Winter mehfil. Lanterns. Someone’s uncle still claps wrong and is loved anyway.", "Sana", "Clap where you like. Just do not steal the pause.", "TAALI",
      "The city sounds like itself: vendors, azaan, a scooter, a taan that makes a dog sit down out of respect. Sana’s voice is not famous. It is occupied, which is better."),
    p(D, "A streaming app offers money for ‘authentic Nawabi vibes’.", "Manager", "Can you do it in forty-five seconds with a drop?", "PING",
      "Sana sends a forty-five-minute riyaz clip by accident, then on purpose. They do not write back. The ustad says this is a good review."),
    p(A, "She walks the chowk at night checking that notes are sleeping in the right throats.", "Sana", "Any of you planning to migrate? Tell me first. I pack better snacks.", "LANTERN",
      "A tabla player salutes with a wrist. Ordinary. Sacred."),
    p(B, "On the Imambara steps, she sings the homeless poet’s ghazal into the open.", "Sana", "If you have no disciple, borrow a city.", "ECHO",
      "The echo agrees to intern. Lucknow, which has lost and kept so much, keeps this too, not in a museum, in a girl who will be late to a bank exam and on time to a note."),
    p(C, "Jasmine in her hair, not as decoration, as a microphone for the dead.", "Narrator", "Sana Qureshi, shepherd of walking songs.", "NIGHT",
      "Windows stay open. The gated complex sells fewer dreams of hush. And in a leaking-cooler room, riyaz begins again, because songs, like cities, need practice more than they need rescue — except when they need rescue, and then they need Sana."),
    p(A, "The salesgirl from the viewing comes for lessons, quietly.", "Salesgirl", "I do not want to sell silence again without knowing what it costs.", "KNOCK",
      "Sana sits her down, starts with the scale, does not start with the lecture. The lecture will arrive in the pauses, where Lucknow keeps its knives and its kindness."),
    p(B, "Festival of lights. The gold birds are not visible. They are busy being music.", "Child", "Aunty, did the songs really walk?", "SPARKLER",
      "Sana says yes, and also that the child must walk them back if they ever run. Responsibility, distributed, is how culture survives developers and uncles and apps."),
    p(D, "Her mother pins a note to the fridge: RENT IS PAID, SING ANYWAY.", "Mother", "I remember the second line now. Annoying child.", "MAGNET",
      "They laugh into cups. The cooler still leaks. The leak keeps time better than a metronome."),
    p(A, "Last page of this book, not of the riyaz.", "Sana", "Tomorrow the same taan, more honest.", "HUM",
      "Honesty, in music, is a muscle. She stretches it in a lane that smells of kebabs and naphthalene, and the couplets, for tonight, stay put, walking only as far as the next breath."),
    p(C, "Moon on the Imambara, round as a pause that nobody sold.", "Narrator", "If your ghazal stands up, follow it. Then teach it to sit.", "FADE SUR",
      "Lucknow inhales. A girl in teal exhales a city back into itself. That is the whole magic, and it will need doing again after the next billboard."),
  ],
};
