import { pg as p } from "../page.js";

const C = "/images/cover-wrestlers-promise.png";
const A = "/images/panel-raja-1.png";
const B = "/images/panel-raja-2.png";
const D = "/images/panel-raja-3.png";
const E = "/images/panel-raja-4.png";

export const wrestlersPromise = {
  id: "wrestlers-promise",
  title: "A Wrestler’s Promise",
  issue: "Book 05",
  genre: "Sports fable",
  place: "Amritsar outskirts",
  minutes: 13,
  accent: "#b91c1c",
  mood: "dust",
  pdf: "/pdfs/A-Wrestler-s-Promise.pdf",
  cover: C,
  hero: "Raja Pahalwan",
  logline:
    "A young wrestler is offered a shortcut of trophies. The mud remembers who he promised to remain, and pride arrives looking like a championship.",
  pages: [
    p(C, "Before medals, there is mud. Before fame, there is a guru’s silence.", "Narrator", "Kushti is not a sport you win. It is a habit you keep.", "THUD",
      "The akhara wakes before the highway. Oil lamps, mustard oil, the slap of feet practising not to lie. Raja Pahalwan runs laps around a peepal that has watched better men become worse."),
    p(A, "Guru-ji’s hands are maps of every throw he ever taught.", "Guru-ji", "Strength is cheap. Who you refuse — that is expensive.", "BREATH",
      "Raja wants both: the throw and the applause. He is twenty-two, which is an age that thinks it can negotiate with gravity and uncles simultaneously."),
    p(E, "Dawn chores: sweep the pit, milk the buffalo, do not skip either.", "Raja", "If I am famous, can someone else sweep?", "SWISH",
      "Guru-ji does not answer with words. He hands Raja the broom as if it were a championship belt that had not yet learned vanity."),
    p(D, "A promoter arrives with gold cups that clink like hollow teeth.", "Promoter", "Throw the next three bouts as I say. The city will chant by Friday.", "CLINK",
      "The offer includes a poster in which Raja’s neck is thicker than truth. Also a scooter. Also a cousin’s wedding paid for. The mud listens."),
    p(D, "Raja looks at the cups, then at the man who taught him to stand.", "Raja", "If the city chants a lie, it is not my name they are using.", "NO",
      "The promoter smiles like someone who has heard no from hungrier men. He leaves a visiting card that smells of hotel soap and other people’s losses."),
    p(A, "Practice that afternoon is uglier. Raja’s mind is doing extra rounds.", "Guru-ji", "Your opponent today is a sentence you almost said yes to.", "SLAP",
      "They wrestle until Raja’s pride is as tired as his shoulders. Tired pride is easier to supervise."),
    p(B, "Pride arrives anyway, as a smoke-and-medal giant in the pit.", "Pride", "Take the scooter. Take the chant. Take a rest from being good.", "WHAM",
      "The villagers gather because smoke in an akhara is never just weather. Raja meets it the only way he trusts: forehead to chest, breath counted, no speech."),
    p(B, "The throw is not pretty. Pretty is for posters.", "Raja", "You can have the noise. I am keeping the mud.", "CRACK",
      "Dust bursts. Children cheer the way children cheer thunder. The giant thins into ordinary evening, which is all pride ever was when asked to show identification."),
    p(E, "After, Raja sweeps. Champions still sweep the pit.", "Guru-ji", "Good. Tomorrow we train at four.", "AMEN",
      "The cups remain unclaimed on a bench until a stray dog knocks one over. The sound is funny. Funny is allowed."),
    p(A, "News travels to the city as a rumour that a boy refused money, which the city finds exotic.", "Reporter", "Any message for the youth?", "MIC",
      "Raja says, Eat breakfast. The quote is printed anyway beside a photo that makes his biceps look like policy."),
    p(D, "The promoter returns with a different mask: patriotism.", "Promoter", "Do it for the district. Do it for the flag. Do it so the other akhara looks small.", "FLAG",
      "Guru-ji spits, politely, into dust. Raja understands that flags are sometimes worn like rented jewellery."),
    p(B, "A real bout: the other akhara’s best, a man named Lakhbir who wrestles clean.", "Lakhbir", "No promoters. Just mud.", "GRIP",
      "They fight as if the pit were a sentence they both want to finish honestly. Raja loses the first fall and does not confuse that with dying."),
    p(B, "Second fall, Raja listens to Guru-ji’s oldest advice: breathe where the other man forgets to.", "Raja", "Now.", "THUD",
      "Lakhbir laughs when he hits the ground, which is how you know the sport is still a sport. They share milk after. The promoter, watching from a car, looks allergic to milk."),
    p(E, "Night. Raja oils Guru-ji’s knees without being asked.", "Guru-ji", "When I am gone, refuse faster. I wasted years on almost.", "OIL",
      "Raja wants to say don’t go. Instead he says four a.m. The peepal rustles like an official who approves."),
    p(C, "A district official offers a stadium if Raja will wear a sponsor on his chest.", "Official", "The children need a hero they can buy in a bottle.", "POP",
      "Raja imagines children drinking a lie. He says the akhara is already a stadium if you count the sky. The official does not have a form for that."),
    p(A, "Winter. The pit hardens. So do excuses.", "Raja", "If I skip one morning, the mud will write my name wrong.", "FROST",
      "He does not skip. A younger boy arrives, hungry in the eyes. Raja hands him the broom first, the way he was handed it, an inheritance of unglamorous light."),
    p(D, "The younger boy is offered the same cups, smaller, shinier.", "Boy", "Bhai, maybe just one thrown fight, for a phone?", "PING",
      "Raja takes him to the dog that knocked the cup. They watch the dog be happy without a brand. It is a ridiculous lesson and it works because the boy likes dogs more than phones, still."),
    p(B, "Festival bout. Marigolds. A crowd that wants a myth.", "Narrator", "Myths are heavy. Better to give them a clean throw instead.", "ROAR",
      "Raja wins without dancing on anyone’s name. He helps Lakhbir up before he lifts his own arms. The camera operators are confused and still film it."),
    p(E, "Guru-ji sleeps through the cheering, which is a kind of review.", "Raja", "We did not become a poster today.", "SNORE",
      "Raja covers him with a khes. The lamps go out one by one like obedient wrestlers."),
    p(A, "Years are not in this book, but mornings are.", "Raja", "The promise was never to the crowd.", "BREATH",
      "It was to the pit, to the man with map-hands, to the boy with the broom, to the version of himself that almost said yes and was allowed to be wrong only once."),
    p(E, "The visiting card is used to scrape mud off a toe.", "Guru-ji", "Finally a use.", "SCRAPE",
      "They laugh, which is also training."),
    p(C, "Oil lamps. A bow. Dust that was never a demon for long.", "Narrator", "Raja Pahalwan, keeper of unfashionable strength.", "FADE",
      "The highway grows louder. The peepal does not care. And in an akhara on the outskirts of Amritsar, a man who could have been a slogan chooses, again, to be a wrestler."),
  ],
};
