export const studio = {
  name: "Katha Studio",
  tagline: "Original Indian comics that move.",
  blurb:
    "Five original graphic stories from Kerala rain to Hampi stone, Howrah night mail to Delhi autos and Punjab akharas. Read them animated. Take them home as PDFs.",
};

export const characters = [
  {
    id: "meera",
    name: "Meera Rainbinder",
    role: "Listener of clouds",
    place: "Alappuzha backwaters",
    portrait: "/images/char-meera.png",
    bio: "Sixteen, stubborn, and the only person in her village who can hear the monsoon as a conversation. She bargains with weather the way other teenagers bargain for extra mango pickle.",
  },
  {
    id: "tara",
    name: "Inspector Tara Sen",
    role: "Night-mail detective",
    place: "Howrah Junction",
    portrait: "/images/char-tara.png",
    bio: "A Kolkata investigator who treats missing letters like missing people. She carries a brass lantern because some evidence only shows up in old light.",
  },
  {
    id: "chotu",
    name: "Chotu Malik",
    role: "Courier of lost things",
    place: "Chandni Chowk",
    portrait: "/images/char-chotu.png",
    bio: "Twelve, goggles always on the forehead, best friends with a golden auto-rickshaw that should not be able to fly — and absolutely does.",
  },
  {
    id: "priya",
    name: "Priya Rao",
    role: "Field archaeologist",
    place: "Hampi",
    portrait: "/images/char-priya.png",
    bio: "She would rather argue with a thousand-year-old shadow than with a museum board. Relics, in her view, are not loot. They are unfinished sentences.",
  },
  {
    id: "raja",
    name: "Raja Pahalwan",
    role: "Akhara wrestler",
    place: "Amritsar outskirts",
    portrait: "/images/char-raja.png",
    bio: "Strong enough to throw a pride-demon, stubborn enough to refuse a pile of trophies. His guru taught him that the mud remembers who you bowed to.",
  },
];

export const comics = [
  {
    id: "monsoon-meera",
    title: "Monsoon Meera",
    issue: "Issue 01",
    genre: "Folk fantasy",
    place: "Kerala backwaters",
    minutes: 4,
    accent: "#0e7c7b",
    mood: "rain",
    pdf: "/pdfs/Monsoon-Meera.pdf",
    cover: "/images/cover-monsoon-meera.png",
    hero: "Meera Rainbinder",
    logline:
      "When the village well cracks dry, a girl who can hear clouds must convince the monsoon to come home.",
    pages: [
      {
        image: "/images/cover-monsoon-meera.png",
        caption: "Alappuzha. The sky has been holding its breath for forty-one days.",
        speaker: "Narrator",
        balloon: "The well sang once. Now it only coughs dust.",
        sfx: "DRY WIND",
      },
      {
        image: "/images/panel-meera-1.png",
        caption: "Meera climbs the tiled roof at dawn, the way other people climb into prayer.",
        speaker: "Meera",
        balloon: "I can hear you sulking up there. Come down and argue properly.",
        sfx: "DRIP… DRIP",
      },
      {
        image: "/images/panel-meera-3.png",
        caption: "The monsoon answers as a cloud with an elephant’s patience and a child’s temper.",
        speaker: "Monsoon",
        balloon: "They forgot the old songs. Why should I remember their fields?",
        sfx: "RUMBLE",
      },
      {
        image: "/images/panel-meera-2.png",
        caption: "Meera offers the only honest bargain: she will teach the children the rain-song again.",
        speaker: "Meera",
        balloon: "If they forget, I’ll remind them. If you forget, I’ll shout at the sky until you don’t.",
        sfx: "CRACK!",
      },
      {
        image: "/images/panel-meera-2.png",
        caption: "The well overflows. Banana leaves become drums. The village learns how to be wet and grateful.",
        speaker: "Amma",
        balloon: "That girl talks to weather like it owes her rent.",
        sfx: "SPLASH",
        reuseNote: true,
      },
      {
        image: "/images/cover-monsoon-meera.png",
        caption: "A single raindrop hangs from Meera’s earring. It never evaporates.",
        speaker: "Monsoon",
        balloon: "Call me when they forget. I like being argued with.",
        sfx: "SOFT RAIN",
      },
    ],
  },
  {
    id: "night-mail",
    title: "Night Mail of Howrah",
    issue: "Issue 02",
    genre: "Noir mystery",
    place: "Howrah Junction",
    minutes: 5,
    accent: "#3d4a8a",
    mood: "noir",
    pdf: "/pdfs/Night-Mail-of-Howrah.pdf",
    cover: "/images/cover-night-mail.png",
    hero: "Inspector Tara Sen",
    logline:
      "Letters vanish from the night mail. Inspector Tara boards a train that should have stopped in 1947.",
    pages: [
      {
        image: "/images/cover-night-mail.png",
        caption: "Platform 9 after midnight smells of wet iron and unfinished goodbyes.",
        speaker: "Narrator",
        balloon: "The living trains keep timetables. The other one keeps promises.",
        sfx: "WHISTLE",
      },
      {
        image: "/images/panel-tara-1.png",
        caption: "A tea-seller swears the missing envelopes boarded a blue engine nobody scheduled.",
        speaker: "Inspector Tara",
        balloon: "People lie. Steam, usually, does not.",
        sfx: "CLINK",
      },
      {
        image: "/images/panel-tara-3.png",
        caption: "Letters burst from a carriage window like white birds that finally remembered the way.",
        speaker: "Tara",
        balloon: "Those aren’t stolen. They’re overdue.",
        sfx: "WHOOSH",
      },
      {
        image: "/images/panel-tara-2.png",
        caption: "Inside: passengers of pale light, each holding a letter they died still carrying.",
        speaker: "Ghost clerk",
        balloon: "Partition scrambled the addresses. We have been sorting ever since.",
        sfx: "HUSH",
      },
      {
        image: "/images/panel-tara-2.png",
        caption: "Tara reads names that still have grandsons in Shyambazar and granddaughters in Dhaka.",
        speaker: "Tara",
        balloon: "Give me the last living addresses. I’ll walk them in daylight.",
        sfx: "STAMP",
      },
      {
        image: "/images/cover-night-mail.png",
        caption: "Dawn at Howrah. The ghost engine bows once, then dissolves into ordinary fog.",
        speaker: "Narrator",
        balloon: "Some detectives close cases. Tara delivers them.",
        sfx: "BELL",
      },
    ],
  },
  {
    id: "golden-auto",
    title: "The Golden Auto",
    issue: "Issue 03",
    genre: "Action comedy",
    place: "Old Delhi",
    minutes: 4,
    accent: "#d97706",
    mood: "kite",
    pdf: "/pdfs/The-Golden-Auto.pdf",
    cover: "/images/cover-golden-auto.png",
    hero: "Chotu Malik & Sonu the Auto",
    logline:
      "A talking auto-rickshaw and a boy with goggles become the city’s unofficial rescue service for lost treasures.",
    pages: [
      {
        image: "/images/cover-golden-auto.png",
        caption: "Chandni Chowk at hour of kites. Gravity is a suggestion.",
        speaker: "Sonu the Auto",
        balloon: "Meter’s off. Adventure’s on. Hold the handle, Chotu.",
        sfx: "VROOM",
      },
      {
        image: "/images/panel-chotu-1.png",
        caption: "Chotu found Sonu sleeping under a tarp, humming an old filmi horn in his dreams.",
        speaker: "Chotu",
        balloon: "Autos don’t talk. Also, autos don’t fly. So we’re already two impossibilities late.",
        sfx: "HONK!",
      },
      {
        image: "/images/panel-chotu-3.png",
        caption: "Dadi’s wedding necklace is in a smuggler van that thinks spice lanes are a racetrack.",
        speaker: "Sonu",
        balloon: "They have a van. We have personality. And altitude.",
        sfx: "SKRRR",
      },
      {
        image: "/images/panel-chotu-2.png",
        caption: "The necklace returns to a grandmother who thought the city had grown too fast to be kind.",
        speaker: "Dadi",
        balloon: "Keep the goggles, beta. The city needs witnesses.",
        sfx: "JINGLE",
      },
      {
        image: "/images/panel-chotu-4.png",
        caption: "Diwali night: fireworks, kites, and a golden auto writing a new route across the sky.",
        speaker: "Chotu",
        balloon: "Tonight we deliver lost things. Tomorrow — maybe homework.",
        sfx: "BOOM",
      },
      {
        image: "/images/cover-golden-auto.png",
        caption: "A hand-painted board appears on a lane wall: LOST? FLAG THE GOLDEN AUTO.",
        speaker: "Narrator",
        balloon: "Delhi has a million vehicles. Only one of them keeps secrets and altitude.",
        sfx: "HONK HONK",
      },
    ],
  },
  {
    id: "ten-shadows",
    title: "Temple of Ten Shadows",
    issue: "Issue 04",
    genre: "Adventure",
    place: "Hampi",
    minutes: 5,
    accent: "#b45309",
    mood: "stone",
    pdf: "/pdfs/Temple-of-Ten-Shadows.pdf",
    cover: "/images/cover-ten-shadows.png",
    hero: "Priya Rao",
    logline:
      "An archaeologist finds a relic that wakes the stone dancers of Hampi — and a smuggler who wants them silent.",
    pages: [
      {
        image: "/images/cover-ten-shadows.png",
        caption: "Moon through a broken vimana. The pillars have been waiting for a listener.",
        speaker: "Narrator",
        balloon: "Hampi does not ruin. It rehearses.",
        sfx: "ECHO",
      },
      {
        image: "/images/panel-priya-1.png",
        caption: "Priya’s torch finds a gold box. Ten carved dancers peel off the stone like wet ink.",
        speaker: "Priya",
        balloon: "Easy. I am not here to steal the sentence. I am here to finish reading it.",
        sfx: "SHHNK",
      },
      {
        image: "/images/panel-priya-3.png",
        caption: "A smuggler’s flashlight cuts the corridor. The shadows freeze, insulted.",
        speaker: "Smuggler",
        balloon: "Relics belong to whoever can carry them out.",
        sfx: "CLICK",
      },
      {
        image: "/images/panel-priya-3.png",
        caption: "Priya does not fight him with fists. She fights him with provenance.",
        speaker: "Priya",
        balloon: "Carry it out and the shadows follow you home. Ask me how I know.",
        sfx: "GRIND",
      },
      {
        image: "/images/panel-priya-2.png",
        caption: "The box returns to its niche. Ten shadows bow, then become carving again.",
        speaker: "Shadow dancer",
        balloon: "Keepers may look. Takers must dance until their feet remember stone.",
        sfx: "HUM",
      },
      {
        image: "/images/cover-ten-shadows.png",
        caption: "Sunrise on the boulders. Priya files a report that the museum will not entirely believe.",
        speaker: "Priya",
        balloon: "Good. Belief is optional. Respect is not.",
        sfx: "BIRDSONG",
      },
    ],
  },
  {
    id: "wrestlers-promise",
    title: "A Wrestler’s Promise",
    issue: "Issue 05",
    genre: "Sports fable",
    place: "Amritsar akhara",
    minutes: 4,
    accent: "#b91c1c",
    mood: "dust",
    pdf: "/pdfs/A-Wrestler-s-Promise.pdf",
    cover: "/images/cover-wrestlers-promise.png",
    hero: "Raja Pahalwan",
    logline:
      "A young wrestler is offered a shortcut of trophies. The mud remembers who he promised to remain.",
    pages: [
      {
        image: "/images/cover-wrestlers-promise.png",
        caption: "Before medals, there is mud. Before fame, there is a guru’s silence.",
        speaker: "Narrator",
        balloon: "Kushti is not a sport you win. It is a habit you keep.",
        sfx: "THUD",
      },
      {
        image: "/images/panel-raja-1.png",
        caption: "Guru-ji’s hands are map-lines of every throw he ever taught.",
        speaker: "Guru-ji",
        balloon: "Strength is cheap. Who you refuse — that is expensive.",
        sfx: "BREATH",
      },
      {
        image: "/images/panel-raja-3.png",
        caption: "A promoter arrives with gold cups that clink like hollow teeth.",
        speaker: "Promoter",
        balloon: "Throw the next three bouts as I say. The city will chant your name by Friday.",
        sfx: "CLINK",
      },
      {
        image: "/images/panel-raja-3.png",
        caption: "Raja looks at the cups, then at the man who taught him to stand.",
        speaker: "Raja",
        balloon: "If the city chants a lie, it is not my name they are using.",
        sfx: "NO",
      },
      {
        image: "/images/panel-raja-2.png",
        caption: "Pride arrives as a smoke-and-medal giant. Raja meets it in the pit, the only courtroom he trusts.",
        speaker: "Raja",
        balloon: "You can have the noise. I am keeping the mud.",
        sfx: "WHAM",
      },
      {
        image: "/images/cover-wrestlers-promise.png",
        caption: "Oil lamps. A bow. The rival dissolves into ordinary dust, which is all pride ever was.",
        speaker: "Guru-ji",
        balloon: "Good. Tomorrow we train at four. Champions still sweep the pit.",
        sfx: "AMEN",
      },
    ],
  },
];

export function comicById(id) {
  return comics.find((c) => c.id === id);
}
